spring.application.name=recipes
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:/Users/neezcha/sqlite/recipes.db
# spring.jpa.hibernate.ddl-auto=create #build new table on start up
spring.jpa.hibernate.ddl-auto=update